# Generated by Django 2.2.10 on 2020-10-27 18:55

import apps.users.models
import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201026_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='cxuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Exactly 5 characters only.', max_length=150, unique=True, validators=[apps.users.models.CxUsernameValidator()], verbose_name='username'),
        ),
    ]
